spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=kanashi2525:)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=d2Vhc2VjdXJla2V5Zm9ySldUdG9rZW5zZWNyZXRrZXkxMjM=
jwt.expiration=86400000